name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thankyou so much for telling us an Issue. We are hearing you to help you.'
        pr-message: 'Hello buddy 👋 Thanks for Joining me. I am looking through it.'